import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Lato } from 'next/font/google';
import { Space_Grotesk } from 'next/font/google';
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import localFont from '@next/font/local';
import { IconsContextProvider } from "@/context/IconsContext";


const inter = Inter({ subsets: ["latin"] });
const lato = Lato({subsets: ['latin'],weight:"400"})
const space = Space_Grotesk({subsets: ['latin'],weight:"400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const circular = localFont({
  src: '../../public/font/Circular Font Family/AvenirLTStd-Medium.otf',
  variable: '--font-circular',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${circular.variable} font-sans`}>
        <Navbar />
        <IconsContextProvider>  
          {children}
        </IconsContextProvider>
        <Footer />
      </body>
    </html>
  );
}
